### ISSUE TITLE
Linux build issue - execute_process error getting child return code: No such file or directory

### ISSUE THREAD

**Issue by tomekit** [Skycoder42/libsodium_dart_bindings#140]
Hi,

I've upgraded from:
```
sodium_libs: ^2.2.0+11
```
to

```
sodium_libs: ^3.4.0+1
```

Executed: `flutter clean`, then went to build using Android Studio. 

Got this error:

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
CMake Error at flutter/ephemeral/.plugin_symlinks/sodium_libs/linux/CMakeLists.txt:19 (execute_process):
  execute_process error getting child return code: No such file or directory

Error: Unable to generate build files
```

Is there anything else I need to do? I've got `libsodium-dev` installed.

Using latest Flutter.
```
[!] Flutter (Channel [user-branch], 3.27.0, on Ubuntu 24.04 LTS 6.8.0-49-generic, locale en_US.UTF-8)
    ! Flutter version 3.27.0 on channel [user-branch] at /opt/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 8495dee1fd (5 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/tomek/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 79.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

**Comment by Unbreathable** [comment]
This same issue happened to me on Windows. I also upgraded to 3.4.0+1, but from 3.3.1. I've downgraded to 3.3.1 and now everything works.

**Comment by Unbreathable** [comment]
Hi, thanks for the quick response. Here is a log from building on Windows:

```bash
[   +5 ms] Building Windows application...
[   +5 ms] <- compile package:chat_interface/main.dart
[        ] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
C:\Users\thisi\OneDrive\Dokumente\Liphium\chat_interface\windows -B C:\Users\thisi\OneDrive\Dokumente\Liphium\chat_interface\build\windows\x64 -G Visual Studio 17 2022 -A x64
-DFLUTTER_TARGET_PLATFORM=windows-x64
[  +47 ms] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
[  +41 ms] Nuget.exe not found, trying to download or use cached version.
[+1039 ms] Feeds used:
[        ]   C:\Users\thisi\.nuget\packages\
[        ]   https://api.nuget.org/v3/index.json
[  +43 ms] Package "Microsoft.Windows.CppWinRT.2.0.210806.1" is already installed.
[ +413 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/sodium_libs/windows/CMakeLists.txt:57 (execute_process):
[        ]   execute_process failed command indexes:
[        ]     1: "Abnormal exit with child return code: no such file or directory"
[        ] -- Configuring incomplete, errors occurred!
[  +21 ms] Building Windows application... (completed in 1,610ms)
[+11341 ms] Error: Unable to generate build files
[        ] "flutter run" took 15,597ms.
[  +29 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:860:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[   +2 ms] Running 2 shutdown hooks
[   +5 ms] Shutdown hooks complete
[  +86 ms] exiting with code 1
```

It's really not more than that, it seems to be, as you said, pointing to the dart run code (this is line 57 of the file that the error mentions).

```cmake
execute_process(
  COMMAND dart run ../tool/libsodium/download.dart windows
  WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  COMMAND_ERROR_IS_FATAL ANY
)
```

**Comment by tomekit** [comment]
I've just realized that: `flutter build linux` executed from the CLI works just fine, what doesn't work is when I build the up from the Android Studio. That's at least how I develop the app. 

![Screenshot from 2024-12-21 15-47-09](https://github.com/user-attachments/assets/8bae5e7e-87ba-4db2-98fa-a187165d1467)

It seems I have path to Dart configured from the Android Studio, so not exactly sure where the problem might be:
![Screenshot from 2024-12-21 15-48-08](https://github.com/user-attachments/assets/e2551834-e817-4ac2-9206-9ce5c9518054)

Fails from the Android Studio:
![Screenshot from 2024-12-21 15-50-28](https://github.com/user-attachments/assets/b881041a-f2e2-4ef5-871a-d959b822cd8d)

**Comment by tomekit** [comment]
Hi @Skycoder42,

Thanks for these improvements. I've upgraded to: `3.4.1+1` and build works fine on all platforms on my end.

One issue that I've started to experience is `msix` build failing: https://pub.dev/packages/msix on Windows. 

I run: `dart run msix:create` and get:
```
Unhandled exception:
Nuget.exe not found, trying to download or use cached version.
CMake Error at flutter/ephemeral/.plugin_symlinks/sodium_libs/windows/CMakeLists.txt:60 (execute_process):
  execute_process error getting child return code: Nie moÅ¼na odnaleÅºÄ‡
  okreÅ›lonego pliku


Unable to generate build files

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
#1      WindowsBuild.build (package:msix/src/windows_build.dart:33:18)
<asynchronous suspension>
#2      Msix._buildMsixFiles (package:msix/msix.dart:107:31)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:102:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:59:5)
<asynchronous suspension>
#5      main (file:///C:/Users/tomas/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.16.8/bin/create.dart:4:3)
<asynchronous suspension>
System nie może odnaleźć określonej ścieżki.
```

The: `Nie moÅ¼na odnaleÅºÄ‡  okreÅ›lonego pliku` message is broken Polish: "Nie można odnaleźć określonego pliku" which roughly translates, to "Can't find the specified file".

and the: `System nie może odnaleźć określonej ścieżki.` message translates to: "System can't find the specified path"

I've tried upgrading `sodium_libs` to `3.4.1+2`, but still the same. 

The `.exe` build, that is: `flutter build windows` works just fine.

**Comment by tomekit** [comment]
Thanks, now I am getting:
```
  execute_process error getting child return code: %1 nie jest prawidÅ‚owÄ…
  aplikacjÄ… systemu Win32
```

which translates to: `Not a valid Win32 application`. 

Later today I might be able to prepare some sample project, where I include both `msix` and and `sodium_libs`, so it's easier for you to have some reproducible environment.

If you would like to try out some new version, I would happily do so.

**Comment by tomekit** [comment]
It also seems that Android debug builds fails from the Android Studio.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sodium_libs:downloadLibsodium'.
> A problem occurred starting process 'command 'dart''
```
That's for the latest: `3.4.2`, this wasn't present in: `2.2.0+11`, I haven't checked which version exactly introduces this issue.

![image](https://github.com/user-attachments/assets/03f93d90-62c1-4cab-8f7a-6e7be172120b)

**Comment by tomekit** [comment]
My project depends directly on `sodium_libs`, so I simply switched to this version for my: `dependencies`.

Android Studio build worked, but there was an error: 
```
Failed to load dynamic library 'libsodium.so': dlopen failed: library "libsodium.so" not found
```

supposedly coming from: 
```dart
final sodium = await SodiumInit.init();
```

I will try this on Windows machine later today.

**Comment by dm-2028** [comment]
I was also seeing this issue on Windows:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sodium_libs:downloadLibsodium'.
> A problem occurred starting process 'command 'dart''
```

 but the dependency override to commit` 49ddd98a700785e51b78b22c191bf645de1edfc8` seems to fix the problem

**Comment by tomekit** [comment]
It seems that newest version addresses the issue for MSIX build on Windows and Android debug build. Linux build works too. 

Thank you for your hard work!

**Comment by Unbreathable** [comment]
I can also confirm that the new version now works for me. Thanks for the amazing work you've been doing, if you have a donation page somewhere let me know (cause I couldn't find one).

Thank you for your hard work even though it was New Year and Christmas and all that!
