### ISSUE TITLE
build failure: libsodium.so not found on latest update

### ISSUE THREAD

**Issue by lukasgit** [Skycoder42/libsodium_dart_bindings#39]
@Skycoder42 

**SUMMARY**

Build fails on latest sodium update.  Failed to load dynamic library 'libsodium.so'

**CONSOLE OUTPUT**

```
E/flutter ( 4835): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libsodium.so': dlopen failed: library "libsodium.so" not found
E/flutter ( 4835): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
E/flutter ( 4835): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
E/flutter ( 4835): #2      SodiumAndroid.loadSodium.<anonymous closure> (package:sodium_libs/src/platforms/sodium_android.dart:16)
E/flutter ( 4835): #3      SodiumInit.init2.<anonymous closure> (package:sodium/src/ffi/sodium_ffi_init.dart:59)
E/flutter ( 4835): #4      SodiumInit.initFromSodiumFFI2.<anonymous closure> (package:sodium/src/ffi/sodium_ffi_init.dart:81)
E/flutter ( 4835): #5      SodiumFFI.fromFactory (package:sodium/src/ffi/api/sodium_ffi.dart:49)
E/flutter ( 4835): #6      SodiumInit.initFromSodiumFFI2 (package:sodium/src/ffi/sodium_ffi_init.dart:80)
E/flutter ( 4835): #7      SodiumInit.init2 (package:sodium/src/ffi/sodium_ffi_init.dart:58)
E/flutter ( 4835): #8      SodiumAndroid.loadSodium (package:sodium_libs/src/platforms/sodium_android.dart:15)
E/flutter ( 4835): #9      SodiumInit.init.<anonymous closure> (package:sodium_libs/src/sodium_init.dart:35)
E/flutter ( 4835): #10     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31)
E/flutter ( 4835): #11     SodiumInit.init (package:sodium_libs/src/sodium_init.dart:30)
E/flutter ( 4835): #12     SodiumHelper.init (package:changefly/src/domain/sodium_helper.dart:10)
E/flutter ( 4835): #13     preSetup (package:changefly/src/main.dart:98)
E/flutter ( 4835): #14     main (package:changefly/src/main.dart:71)
E/flutter ( 4835): <asynchronous suspension>
E/flutter ( 4835): 

Application finished.
```

**OVERRIDE** `pubspec.yaml`:

```
  sodium_libs: 2.0.0
  sodium: 2.0.1
```

**Comment by alexandrim0** [comment]
I faced same issue

**Comment by lukasgit** [comment]
@Skycoder42 works now, thank you.
